### ISSUE TITLE
No module named bs4

### ISSUE THREAD

**Issue by smabbasht** [0WN463/bobcat#1]
Hello, Thankyou for this amazing tool.

I was just trying to install it and on first launch it gave the attached error (I use arch btw)
```Traceback (most recent call last):
  File "/opt/miniconda3/bin/bobcat", line 33, in <module>
    sys.exit(load_entry_point('bobcat==0.0.1', 'console_scripts', 'bobcat')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/bin/bobcat", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/miniconda3/lib/python3.11/site-packages/bobcat/bobcat.py", line 10, in <module>
    from . import kattis
  File "/opt/miniconda3/lib/python3.11/site-packages/bobcat/kattis.py", line 13, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'```

**Comment by smabbasht** [comment]
The issue got resolved when I installed bs4 from pip but I think the issue is with the setup script, there should be bs4 instead of beautifulsoup4 if the package comes under this title now on pip.

**Comment by smabbasht** [comment]
```
$ bobcat
User: abbastaqvi81@gmail.com
Password:
Traceback (most recent call last):
  File "/opt/miniconda3/bin/bobcat", line 33, in <module>
    sys.exit(load_entry_point('bobcat==0.0.1', 'console_scripts', 'bobcat')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/bobcat/bobcat.py", line 29, in main
    s = kattis.login(user, password)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/bobcat/kattis.py", line 39, in login
    soup = BeautifulSoup(res.text, features='lxml')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smabbasht/.local/lib/python3.11/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

I am getting this error while trying to login

**Comment by 0WN463** [comment]
Sorry, I am not that active on GitHub, but I suppose the error is resolved if you install the `lxml` parser for bs4.

If you have suggestion for the setup_tool script, please feel free to contribute, I am new to Python packaging
